param([string]$ControlPath='publisher/release.json')
$ErrorActionPreference='Stop'

$cfg=Get-Content -LiteralPath $ControlPath -Raw | ConvertFrom-Json
$work=Join-Path $env:RUNNER_TEMP ('xenus-publish-'+[guid]::NewGuid().ToString('N'))
$download=Join-Path $work 'base.zip'
$extract=Join-Path $work 'extract'
$outRoot=Join-Path $work 'package-root'
$payloadOut=Join-Path $outRoot 'XenusDRO2Tool'
$dist=Join-Path (Get-Location) 'dist'
New-Item -ItemType Directory -Force -Path $work,$extract,$payloadOut,$dist | Out-Null

Write-Host "Downloading base package: $($cfg.basePackageUrl)"
Invoke-WebRequest -UseBasicParsing -Uri $cfg.basePackageUrl -OutFile $download
Expand-Archive -LiteralPath $download -DestinationPath $extract -Force
$items=@(Get-ChildItem -LiteralPath $extract -Force)
$base=$extract
if($items.Count -eq 1 -and $items[0].PSIsContainer){$base=$items[0].FullName}

Copy-Item -LiteralPath (Join-Path $base '*') -Destination $payloadOut -Recurse -Force

# Replace the old runtime with the new build identity while preserving the proven runtime logic.
$runtime=@(Get-ChildItem -LiteralPath $payloadOut -Filter 'Xenus_DRO2_Tool_*.ps1' -File)
if($runtime.Count -ne 1){throw "Expected exactly one runtime PS1 in base package; found $($runtime.Count)"}
$text=Get-Content -LiteralPath $runtime[0].FullName -Raw
foreach($r in @($cfg.replacements)){
    if(-not $text.Contains([string]$r.from)){throw "Required replacement source not found: $($r.from)"}
    $text=$text.Replace([string]$r.from,[string]$r.to)
}
Remove-Item -LiteralPath $runtime[0].FullName -Force
$newRuntime=Join-Path $payloadOut ([string]$cfg.runtimeFile)
[System.IO.File]::WriteAllText($newRuntime,$text,(New-Object System.Text.UTF8Encoding($true)))

# Use the current updater template. This lets updater fixes ship without rebuilding the EXE/bridge.
Copy-Item -LiteralPath 'publisher/updater-template.ps1' -Destination (Join-Path $payloadOut 'XenusDRO2Updater.ps1') -Force

# Regenerate the developer console helper so it always points at the current runtime filename.
$bat="@echo off`r`ncd /d `"%~dp0`"`r`npowershell.exe -NoProfile -ExecutionPolicy Bypass -File `"%~dp0$($cfg.runtimeFile)`"`r`npause`r`n"
[System.IO.File]::WriteAllText((Join-Path $payloadOut 'DEV_VISIBLE_CONSOLE.bat'),$bat,[System.Text.Encoding]::ASCII)

$readme=@"
Xenu's DRO2 Tool - $($cfg.version)

Published automatically by GitHub Actions.
Channel: $($cfg.channel)
Release tag: $($cfg.tag)
Base binary package: $($cfg.basePackageUrl)

The launcher EXE and DRO2 bridge are carried forward from the proven binary baseline unless a future build pipeline explicitly replaces them.
The runtime/updater files are regenerated by the publisher workflow.
"@
Set-Content -LiteralPath (Join-Path $payloadOut 'README.txt') -Value $readme -Encoding UTF8
Set-Content -LiteralPath (Join-Path $payloadOut 'SHA256.txt') -Value 'Package SHA256 is published in the online update manifest.' -Encoding UTF8

$asset=Join-Path $dist ([string]$cfg.assetName)
if(Test-Path $asset){Remove-Item -LiteralPath $asset -Force}
Compress-Archive -Path $payloadOut -DestinationPath $asset -CompressionLevel Optimal
Write-Host "Built $asset"
